[random]
seed = 0

[path]
# base = "./output/FullBandNet"
base = "/model/FullBandNet"

[dataloader]
batch_size = 512
num_workers = 8
drop_last = false

[dataset]
sr = 16000
n_fft = 512
win_len = 512
hop_len = 256
audio_len = 3.072
limit = 0

[model]
num_freqs = 257
hidden_size = 512
num_layers = 3
dropout = 0
look_ahead = 2

[train]
use_amp = true
resume = false
optimizer = "Adam"
lr = 1e-3
epochs = 9999
save_checkpoint_interval = 1
valid_interval = 50
clip_grad_norm_value = 10.0
audio_visual_samples = 20

[inference]
audio_visual_samples = 20
