[datasets.path]
clean = "../datasets/DNS_INTERSPEECH_2021/clean/mandarin_speech"
noise = "../datasets/DNS_INTERSPEECH_2021/noise"

[synthesizer.path]
train_clean = "../datasets/DNS_INTERSPEECH_2021/clean/mandarin_speech"
noise = "../datasets/DNS_INTERSPEECH_2021/noise"
valid = "../datasets/DNS_INTERSPEECH_2021/valid"
test = "../datasets/DNS_INTERSPEECH_2021/test"

[synthesizer.args]
sr = 16000
audio_length = 3.072
silence_length = 0.2
total_hours = 10
snr_range = [-10, 20]
