[datasets.path]
zip = "../data/data117156/DNS_INTERSPEECH_2021.zip"
clean = "../data/data117156/DNS_INTERSPEECH_2021/clean/mandarin_speech"
noise = "../data/data117156/DNS_INTERSPEECH_2021/noise"

[synthesizer.path]
train_clean = "../data/data117156/DNS_INTERSPEECH_2021/clean/mandarin_speech"
noise = "../data/data117156/DNS_INTERSPEECH_2021/noise"
valid = "../data/data117156/DNS_INTERSPEECH_2021/valid"
test = "../data/data117156/DNS_INTERSPEECH_2021/test"

[synthesizer.args]
sr = 16000
audio_length = 3.072
silence_length = 0.2
total_hours = 0.5
snr_range = [-10, 20]
