[random]
seed = 0

[path]
root = "../../data/data119056"
# root = "D:/ML/datasets"
zip = "dns_interspeech_2021_mandarin_100h.zip"

[dataloader]
batch_size = 20
num_workers = 4
drop_last = false

[dataset]
sr = 16000
n_fft = 512
win_len = 512
hop_len = 256
audio_len = 3.072
limit = 0

[model]
num_freqs = 257
fullband_num_neighbors = 0
subband_num_neighbors = 15
fullband_hidden_size = 512
subband_hidden_size = 384
fullband_num_layers = 2
subband_num_layers = 2
num_groups_in_drop_band = 2
dropout = 0
look_ahead = 2

[train]
use_amp = true
resume = false
optimizer = "Adam"
lr = 1e-3
epochs = 500
save_checkpoint_interval = 1
valid_interval = 5
clip_grad_norm_value = 10.0
audio_visual_samples = 20

[inference]
audio_visual_samples = 20
